### ISSUE TITLE
/add user flags error

### ISSUE THREAD

**Issue by Aquillacomputingsystem** [mtrogman/managarr#23]
adding user in discord. enters data correctly but then states the interaction fails. 
Log has this error

discord.ui.view Ignoring exception in view <FourKView timeout=180.0 children=1> for item <FourKSelector placeholder='4K?' min_values=1 max_values=1 disabled=False options=[<SelectOption label='Yes' value='Yes' description=None emoji=None default=False>, <SelectOption label='No' value='No' description=None emoji=None default=False>, <SelectOption label='Cancel' value='cancel' description=None emoji=None default=False>]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ui/view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "/app/modules/discordFunctions.py", line 189, in callback
    await self.handle_new_user(interaction)
  File "/app/modules/discordFunctions.py", line 231, in handle_new_user
    term_length = mathFunctions.calculate_term_length(server, self.information['paidAmount'], self.information['4k'])
  File "/app/modules/mathFunctions.py", line 28, in calculate_term_length
    years_paid_for = amount / twelve_month_price
ZeroDivisionError: float division by zero
ERROR:discord.ui.view:Ignoring exception in view <FourKView timeout=180.0 children=1> for item <FourKSelector placeholder='4K?' min_values=1 max_values=1 disabled=False options=[<SelectOption label='Yes' value='Yes' description=None emoji=None default=False>, <SelectOption label='No' value='No' description=None emoji=None default=False>, <SelectOption label='Cancel' value='cancel' description=None emoji=None default=False>]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ui/view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "/app/modules/discordFunctions.py", line 189, in callback
    await self.handle_new_user(interaction)
  File "/app/modules/discordFunctions.py", line 231, in handle_new_user
    term_length = mathFunctions.calculate_term_length(server, self.information['paidAmount'], self.information['4k'])
  File "/app/modules/mathFunctions.py", line 28, in calculate_term_length
    years_paid_for = amount / twelve_month_price
ZeroDivisionError: float division by zero

**Comment by mtrogman** [comment]
Speaking to Aquilla via Discord to work out issue.

Initial inspection is that potentially config doesnt have a 12 month value set as bottom of code has this:
years_paid_for = amount / twelve_month_price
ZeroDivisionError: float division by zero

Believe error should be corrected with after this code is merged
[bugIssue23-DivideByZeroError](https://github.com/mtrogman/managarr/tree/bugIssue23-DivideByZeroError)
